import NavBar from '@/components/navbar'
import FeaturePage from '@/components/pages/feature/page'
import { Inter } from 'next/font/google'
import './globals.css'
import WhotwPage from '@/components/pages/whotw/page'
import PricingPage from '@/components/pages/pricing/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div id='home' className=' w-full'>
					<NavBar />
					<main className='flex flex-col justify-around items-center'>
						{children}
						<FeaturePage />
						<WhotwPage />
						<PricingPage />
					</main>
				</div>
			</body>
		</html>
	)
}
